name: wayrapp_mobile
description: WayrApp Mobile - Flutter application for language learning
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # HTTP Client
  dio: ^5.7.0
  
  # Secure Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  
  # Navigation
  go_router: ^16.2.0
  
  # Forms and Validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.1.1
  
  # Network State
  connectivity_plus: ^6.0.5
  
  # UI Components
  cupertino_icons: ^1.0.8
  
  # JSON Serialization
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  
  # Testing
  mockito: ^5.4.4
  
  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/