# docs/_config.yml

# --- Información del Sitio ---
title: WayrApp API Documentation
description: >- # El ">-" significa que el texto puede tener múltiples líneas.
  Comprehensive API documentation for the WayrApp open-source language learning platform.
  Find everything you need to integrate with our backend.
theme: jekyll-theme-minimal # Un tema limpio y moderno, perfecto para documentación.

# --- Navegación del Sitio ---
# Esto creará los enlaces en la barra de navegación de tu sitio.
# El 'title' es lo que el usuario ve, y la 'url' es el enlace al archivo.
nav:
  - title: API Overview
    url: /API_OVERVIEW
  - title: Authentication
    url: /AUTHENTICATION
  - title: Users
    url: /USERS
  - title: Content
    url: /CONTENT
  - title: Lessons & Exercises
    url: /LESSONS_EXERCISES
  - title: Progress
    url: /PROGRESS
  - title: Packaged Content
    url: /PACKAGED_CONTENT_API
  - title: Pagination & Filtering
    url: /PAGINATION_AND_FILTERING
  - title: Database Setup
    url: /DATABASE_SETUP

# --- Plugins y Metadatos ---
plugins:
  - jekyll-seo-tag # Añade automáticamente etiquetas meta para SEO (Google, etc.)