# WayrApp Backend Documentation Configuration

title: WayrApp API Documentation
description: >-
  Comprehensive API documentation for the WayrApp open-source language learning platform.
  Find everything you need to integrate with our backend.
theme: jekyll-theme-minimal
baseurl: "/wayrapp"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-seo-tag

# Navigation structure
nav:
  - title: API Overview
    url: /API_OVERVIEW
  - title: Authentication
    url: /AUTHENTICATION
  - title: Users
    url: /USERS
  - title: Content
    url: /CONTENT
  - title: Lessons & Exercises
    url: /LESSONS_EXERCISES
  - title: Progress
    url: /PROGRESS
  - title: Pagination & Filtering
    url: /PAGINATION_AND_FILTERING
  - title: Packaged Content
    url: /PACKAGED_CONTENT_API
  - title: Database Setup
    url: /DATABASE_SETUP

# SEO settings
author: Exequiel Trujillo
twitter:
  username: wayrapp
  card: summary_large_image

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/