source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "jekyll-theme-minimal", "~> 0.2.0"
gem "jekyll-seo-tag", "~> 2.8.0"
gem "jekyll-sitemap", "~> 1.4.0"
gem "jekyll-feed", "~> 0.17.0"
gem "webrick", "~> 1.8"